export enum EPokemonType {
  NORMAL = 'normal',
  POISON = 'poison',
  GRASS = 'grass',
  FIRE = 'fire',
  WATER = 'water',
  FLYING = 'flying',
  ELECTRIC = 'electric',
  GROUND = 'ground',
  BUG = 'bug',
  FAIRY = 'fairy',
  ROCK = 'rock',
  GHOST = 'ghost',
  STEEL = 'steel',
  PSYCHIC = 'psychic',
  ICE = 'ice',
  DRAGON = 'dragon',
  DARK = 'dark',
  SHADOW = 'shadow',
  UNKNOWN = 'unknown',
}

export const POKEMON_TYPE = {
  [EPokemonType?.NORMAL]: '#b0ac9f',
  [EPokemonType?.GRASS]: '#89b889',
  [EPokemonType?.POISON]: '#805eab',
  [EPokemonType?.FIRE]: '#de2d2c',
  [EPokemonType?.WATER]: '#8cc4d1',
  [EPokemonType?.FLYING]: '#b09066',
  [EPokemonType?.ELECTRIC]: '#e9bc3d',
  [EPokemonType?.GROUND]: '#8f6027',
  [EPokemonType?.BUG]: '#7cba1e',
  [EPokemonType?.FAIRY]: '#ed8078',
  [EPokemonType?.ROCK]: '#7f7d8a',
  [EPokemonType?.GHOST]: '#6262ab',
  [EPokemonType?.STEEL]: '#8b8a92',
  [EPokemonType?.PSYCHIC]: '#e85c92',
  [EPokemonType?.ICE]: '#70bad1',
  [EPokemonType?.DRAGON]: '#7659d4',
  [EPokemonType?.DARK]: '#402b31',
  [EPokemonType?.SHADOW]: '#5745a3',
  [EPokemonType?.UNKNOWN]: '#222537',
};
